In [1]:
mat <- matrix(1:6,nrow=2)

In [2]:
mat

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [3]:
mat <- matrix(1:6,ncol=2)
mat

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [4]:
mat <- matrix(1:6,ncol=2,byrow=TRUE)
mat

[,1] [,2]
[1,] 1    2   
[2,] 3    4   
[3,] 5    6

In [6]:
matrix(1:3,ncol=2,nrow=3,byrow = TRUE)
matrix(1:3,ncol=2,nrow=3,byrow = FALSE)

[,1] [,2]
[1,] 1    2   
[2,] 3    1   
[3,] 2    3

[,1] [,2]
[1,] 1    1   
[2,] 2    2   
[3,] 3    3

In [11]:
cbind(1:3,2:10)
rbind(1:3,2:4)

[,1] [,2]
 [1,] 1     2  
 [2,] 2     3  
 [3,] 3     4  
 [4,] 1     5  
 [5,] 2     6  
 [6,] 3     7  
 [7,] 1     8  
 [8,] 2     9  
 [9,] 3    10

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 2    3    4

In [16]:
m <- matrix(1:6,nrow=2,byrow = TRUE)
cbind(m,8:9)
rbind(m,7:9)

[,1] [,2] [,3] [,4]
[1,] 1    2    3    8   
[2,] 4    5    6    9

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [17]:
m

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [19]:
rownames(m) <- c("row1","row2")
colnames(m) <- c("col1","col2","col3")
m

col1 col2 col3
row1 1    2    3   
row2 4    5    6

In [20]:
m <- matrix(1:6,nrow=2,byrow = TRUE,dimnames = list(c("row1","row2"),c("col1","col2","col3")))
m

col1 col2 col3
row1 1    2    3   
row2 4    5    6

In [21]:
mint <- matrix(1:6,nrow=2,byrow = TRUE)
mchar <- matrix(LETTERS[1:6],nrow=2,byrow = TRUE)
cbind(mint,mchar)

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    2    3    A    B    C   
[2,] 4    5    6    D    E    F