In [1]:
mint <- matrix(1:6,nrow=2,byrow = TRUE)
mint[2,]

[1] 4 5 6

In [2]:
m <- matrix(sample(1:15,12),nrow=3)
m

[,1] [,2] [,3] [,4]
[1,] 6    13    4   12  
[2,] 9     1   10    7  
[3,] 8     2   14   11

In [6]:
m[3,c(3,4)]

[1] 14 11

In [7]:
m[6]

[1] 2

In [8]:
m[c(1,3),c(1,3)]

[,1] [,2]
[1,] 6     4  
[2,] 8    14

In [12]:
m[c(TRUE,FALSE),c(TRUE,TRUE,FALSE,FALSE)]

[,1] [,2]
[1,] 6    13  
[2,] 8     2